version: "3.9"

services:

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI (guest/guest)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  orders-db:
    image: postgres:16-alpine
    container_name: orders-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${ORDER_DB_NAME}
    volumes:
      - orders_db_data:/var/lib/postgresql/data
      - ./order-service/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${ORDER_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  payments-db:
    image: postgres:16-alpine
    container_name: payments-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${PAYMENT_DB_NAME}
    volumes:
      - payments_db_data:/var/lib/postgresql/data
      - ./payment-service/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${PAYMENT_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10



  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    container_name: payment-service
    depends_on:
      payments-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      DB_HOST: payments-db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${PAYMENT_DB_NAME}
      SERVER_PORT: ${PAYMENT_SERVICE_PORT}
      GRPC_PORT: ${GRPC_PORT}
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    ports:
      - "8081:8081"
      - "50051:50051"

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    depends_on:
      orders-db:
        condition: service_healthy
      payment-service:
        condition: service_started
    environment:
      DB_HOST: orders-db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${ORDER_DB_NAME}
      PAYMENT_GRPC_ADDR: payment-service:${GRPC_PORT}
    ports:
      - "8080:8080"

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    restart: on-failure

volumes:
  rabbitmq_data:
  orders_db_data:
  payments_db_data: